categories:
  - title: 💥 Breaking changes
    label: "breaking-change"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📝 documentation"
    labels:
      - "doc"
      - "readme"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |
  ## What’s Changed

  $CHANGES

  Changelog: [`$PREVIOUS_TAG...`](https://github.com/PAICookers/PAITest/compare/$PREVIOUS_TAG...)
